### ISSUE TITLE
Helm deploy support 

### ISSUE THREAD

**Issue by ElanHasson** [kbterm/kubeterm#2]
### What would you like to be added?

It'd be great to be able to manage helm 3 deploys and upgrades.

Could be accomplished how rancher does it by running a dynamically created k8s job to perform the task.

### Why is this needed?

Helm deployment when on the go!

**Comment by daimg** [comment]
Hi, thanks for this request. 
Helm chart supporting, indeed, is a important functionality, which I am originally thinking may be more useful when working on desktop (so, it will be available on desktop version in the plan). I would support it as higher priority on kubeterm mobile version per this request.
Because helm cli is not available on android/ios, the solution may require to install some components(something like ranche helm-controller, kubeApps, etc) into the cluster, to manage the charts in cluster, then kubeterm can talk with the comoponets to manage the charts.  From your perspective, do you think new component installation in cluster is convenient or acceptable?

**Comment by ElanHasson** [comment]
Hi,

Yeah, I think deploying a job to perform the helm install/upgrade is acceptable, as long as the job itself is open source so that way those who use it can verify what is running in their cluster.

**Comment by daimg** [comment]
As phase 1, list and view helm charts/releases installed in cluster has been supported in v1.1.2.

**Comment by daimg** [comment]
Helm install, upgrade, rollback and uninstall have been supported since v1.2.4. 
(Note: Android version has been released, and ios version is waiting for App Store review.)
