### ISSUE TITLE
Add project name to cluster list

### ISSUE THREAD

**Issue by PabloStrange** [kbterm/kubeterm#4]
### What would you like to be added?

I would like to see the name of the project in the cluster list.

### Why is this needed?

I my case it is rather an unfortunate naming issue. I'm deploying my projects and clusters to Google Cloud with Terraform and decided to name the Kubernetes Cluster simply "gke". 

So If I add or view a cluster it looks like this:
![screenshot_20240111_115039](https://github.com/kbterm/kubeterm/assets/21281633/0f4d4bfc-7abd-4e81-a300-748249684979)
![screenshot_20240108_163500](https://github.com/kbterm/kubeterm/assets/21281633/eb9a82be-a41a-4a80-bbfb-3cbfd618fd0d)

**Comment by daimg** [comment]
Thanks for the suggestion.  It could be supported in next release. (Cluster name in list is also editable locally if you'd like)
Because gcp project name seem to be also duplicatable, do you need to show cluster's project ID in this app somewhere?

Cluster name in kubeterm must be unique currently, the conflicted one is appended with a suffixed number as show in the screenshot. I am thinking whether same name should be accepted, to make the list more clear and straightforward. (may need more check to find real duplicated cluster.)

**Comment by daimg** [comment]
It is supported in V1.2.0 now.
Note: please reload gke clusters again to download project info into your device.
