### ISSUE TITLE
Unable to connect to GKE

### ISSUE THREAD

**Issue by 880831ian** [kbterm/kubeterm#6]
### Platform

macOS

### What happened?

I currently get errors when using macOS and IOS

macOS:
When using kube/config, `Invalid config: auth plugin interactiveMode<null> not supported` will appear.

<br>

<img width="790" alt="截圖 2024-08-30 凌晨12 54 16" src="https://github.com/user-attachments/assets/59de76de-f251-4838-b83d-4de52624cbbc">

<br>

---

If you use Google Auth Login and Service Account of macOS and IOS

```
HandshakeException: Handshake error in client (OS Error:
CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))
```
will appear

<br>

![IMG_2313](https://github.com/user-attachments/assets/940bb362-5424-45fb-a8af-4a12234b1c47)

<br>

Both macOS and IOS use APP version 1.3.2. macOS is downloaded from github

<br>

By the way, the design APP page is very nice. I hope I can use it soon. Please confirm again.

### App version

Version 1.3.2 (83)

### Cloud provider

GCP

**Comment by daimg** [comment]
Thanks for reporting issues.

Issue1: kubeconfig error: Invalid config: auth plugin interactiveMode<null> not supported. 

It looks like field interactiveMode in kubeconfig is missing. 
Could you please check your kubeconfig about ExecConfig of gcp cluster, whether this field is included?

```
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      xxxxx
      xxxxx
      interactiveMode: IfAvailable
```

As a workaround, you may add "interactiveMode: IfAvailable" into kubeconfig and try again. 
(After checking the definition again, I find this field could be optional in some versions. I may fix this issue later.)


Issue2: handshake error CERTIFICATE_VERIFY_FAILED

Yes, this is an known issue. (happened on some version of macos/ios, and I am still in figuring out the root cause). You may disable TLS verification in Kubeterm's settings as a workaround.  Turn on following flag.
Settings->Connectivity-> Disable TLS verify

Note: This config will only be valid for new imported cluster, so please turn on this flag, then import your cluster, by login or service account, again.
(After importing succeed, you don't need keep this flag on)
