### ISSUE TITLE
mTLS cert from Android Keystore/service token when initiating HTTPS request

### ISSUE THREAD

**Issue by aryasenna** [kbterm/kubeterm#7]
### Platform

Android

### What would you like to be added?

Kubeterm uses User certificate installed on device to initiate TLS connection to remote kubernete cluster, or lternatively with service token embedded to header. 

### Why is this needed?

Use case is when you have gatekeeper reverse proxy such as Cloudflare access protecting your Kubernete controller instance.

One can use mTLS or service token to authenticate the HTTPS connection to kubernete. 

In the Desktop platform, the Web browser-like engine handles this natively, as you will be asked to send already installed cert. 

In Android, the user cert in Keystore is not requested unless the user has a Webview open. 

Just to be clear, I'm talking about mTLS/service token used to establish HTTPS connection on the first place,  NOT to login to kubernete API itself. 

Normally with OKHTTP being used Android should handle this transparently, the workflow is a WebView browser is open and we choose which User certificate to send. When the WebView is closed, the same HTTPS connection is re used.

**Comment by daimg** [comment]
Thanks for the request.
Per my understanding, you are trying to set a https proxy, with client certification auth or token auth, to connect k8s cluster. Is that correct?

Kubeterm does respect system proxy env, but currently user can't set the proxy manually. 

I may add a global or k8s cluster level setting in kubeterm for proxy. Will this address your issue?

**Comment by aryasenna** [comment]
Hello, thanks for checking 😊

I'm talking about **reverse** proxy sitting in front of kubernete cluster, so the device system proxy setting has no effect whatsoever. Those setting are for **forward** proxy, if I understand correctly.

The said reverse proxy setting requires either mTLS (clirnt cert) or custom HTTP headers with a service token. 

Maybe these links explain better than me:

https://www.cloudflare.com/en-gb/learning/access-management/what-is-mutual-tls/

https://xoltawn.medium.com/how-to-use-mtls-in-flutter-da698e5700ef

https://api.flutter.dev/flutter/dart-io/SecurityContext-class.html

**Comment by daimg** [comment]
Thanks for the info. 
The case might be easy to be supported, I think, if it is about using client cert for mTLS, not a transparent forward proxy for k8s cluster.

Currently, kubeterm already use client cert (client-certificate-data of users section) in kubeconfig, to perform mTLS handshake with server, after it load the kubeconfig. No more additional config needed. 
So, adding the client certificate into kubeconfig would be able to solve the issue.

Because your reverse proxy in on tls termination mode, I think, you may also need some cert config in proxy to connect k8s cluster in backend.

**Comment by aryasenna** [comment]
>Because your reverse proxy in on tls termination mode, I think, you may also need some cert config in proxy to connect k8s cluster in backend.

Unfortunately, this is the case. After establishing TLS to the reverse proxy, I need to give an additional service token to K8s's backend.

From my understanding kubenernte client like kubectl and kubeterm expects that if `client-certificate-data`field exists, then `token` field will be ignored. Correct?

The reverse proxy in question is Cloudflalre, and it will only send mTLS to the Kubernete backend using its own CA. I'm not sure if I want to make the CF CA trustable on my Kubernete backend.

Is it possible to implement custom HTTP headers per cluster config instead?

**Comment by daimg** [comment]
Kubeterm support to use both client-certificate-data and token as long as they exist in kubeconfig, handshake using client cert and then send request with token. So, token from kubeterm to proxy then k8s cluster is not a problem.

The issue seems to be how to setup tls connection between proxy and k8s server. You may have to install ca from k8s cluster into proxy, or use cloudflare trust ca in k8s cluster as you mentioned.

mTLS between proxy and k8s cluster is not necessary.

Other option, for example, deploy your own proxy
https://cloud.google.com/kubernetes-engine/docs/tutorials/private-cluster-bastion

**Comment by aryasenna** [comment]
Hi, I did not know you could specify both the token and client cert inside a kubeconfig file, and kubectl will use both.

Yes, I confirm this method is working. Thanks :) So, I close this issue,
